### ISSUE TITLE
Generated packets aren't seen in monitor mode from another RT-AC86U with Nexmon CSI.

### ISSUE THREAD

**Issue by Davide-Zamboni** [seemoo-lab/nexmon_tx_task#1]
Firstly thank you for the huge help in implementing frame injection for bcm4366c0. 

Now I have two Asus RT-AC86U routers, one for monitoring using [Nexmon CSI Extraction](https://github.com/seemoo-lab/nexmon_csi), the other with this frame injection patch.
Everything works without errors but I can't sniff any packet coming from the router that generates packets. Probably I'm messing with the parameters and can't find the right one. 

What configuration can I use to make my setup work / what configuration have you used for your tests?

Here's my setup:

On the router that generates frames:

- Wi-Fi Interface configuration: ` /usr/sbin/wl -i eth6 chanspec 157/80`
- tx_task.sh: The same as the provided one in the utils folder ( `bandwidth=1`)
- `/jffs/tx_task.sh eth6 init`
- `/jffs/tx_task.sh eth6 start`

On the router that sniffs packets:

- `./makecsiparams -c 157/80 -C 4 -N 1 -b 0x88`
- `./nexutil -Ieth6 -s500 -b -l34 -vm+IBFAGIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`
- `/usr/sbin/wl -i eth6 monitor 1`

Thank you in advance.
@jlinktu

**Comment by jlinktu** [comment]
Hi @Davide-Zamboni,

you are setting `0x88` as byte filter with `makecsiparams ... -b 0x88`, which basically means filter for QoS Data frames.
As documented in [Default configuration](https://github.com/seemoo-lab/nexmon_tx_task#default-configuration), the first byte of the frame defined in `tx_task.sh` begins with `0x08` (a normal Data frame), thus, you want to put `makecsiparams ... -b 0x08` instead.
If you are unsure when filtering, try to first use monitor mode without CSI extraction and have a look with Wireshark or something similar.

As you are using channel `157/80` on the extractor but are transmitting with `bandwidth=1` (20 MHz), only a subset of the extracted CSI will look _filled_. If you want all the subcarriers of the extracted 80 MHz CSI to be useful try with `bandwidth=3` instead.

**Comment by Davide-Zamboni** [comment]
@jlinktu ,
thanks for the piece of advice. By following your suggestion I also tried the monitor mode with Wireshark and curiously discovered that there isn't any packet coming from the ASUS router that generates frames, even if I launched the `tx_task.sh init` and `tx_task.sh start` commands. 
It seems very strange since the two commands work correctly and they both print `done` without errors. Maybe there's something to change in the `tx_task.sh` beside the bandwidth setting. 
What overall configuration have you used for your tests?

**Comment by jlinktu** [comment]
I have two Asus RT-AC86U, one is used as monitor device (`mon`), and one as transmitter (`tx`). Find a log of what I did to confirm the patch is working in the following:

Setup `tx`:
```
$ cd nexmon/
$ source setup_env.sh
$ cd patches/bcm4366c0/10_10_122_20/nexmon_tx_task
$ make install-firmware REMOTEADDR=<tx address>
$ sed -n 47,58p utils/tx_task.sh
spatial_mode=0    # 0: OFF, 1: ON, 255: AUTO, might enable STBC -> leave OFF if unwanted
periodic=1        # 0: single transmission, 1: repetitive transmissions
tx_delay=500      # delay in milliseconds between repetitive transmissions and before the first transmission
repetitions=-1    # number of repetitive transmissions, -1 means infinite
bandwidth=3       # bandwidth (1, 2, 3 : 20, 40 or 80 MHz)
mcs=4             # VHT Modulation Coding Scheme
spatial_streams=4 # number of spatial strams (1 - 4)

# Data frame, To DS: 0 From DS: 1, Receiver/Destination address: 00:11:22:33:44:55, Transmitter address/BSS Id: 00:11:22:33:44:66, Source address: 00:11:22:33:44:77, no payload
frame_length=24
frame_bytes='\x08\x02\x00\x00\x00\x11\x22\x33\x44\x55\x00\x11\x22\x33\x44\x66\x00\x11\x22\x33\x44\x77\x00\x00'
$ make install-util REMOTEADDR=<my transmitters address>
$ ssh admin@<tx address>
admin@RT-AC86U:/jffs# wl -i eth6 country US
admin@RT-AC86U:/jffs# wl -i eth6 chanspec 157/80
admin@RT-AC86U:/jffs# wl -i eth6 up
admin@RT-AC86U:/jffs# ifconfig eth6 up
admin@RT-AC86U:/jffs# ./tx_task.sh eth6 init
admin@RT-AC86U:/jffs# dmesg | grep NEXMON | tail -n1
CONSOLE: 027039.022 NEXMON wlc_ioctl_hook: initialized tx task (delay 500ms, periodic 1, repetitions -1, rate 0xc2030044, frame length 24)
admin@RT-AC86U:/jffs# ./tx_task.sh eth6 start
done
admin@RT-AC86U:/jffs# dmesg | grep NEXMON | tail -n1
CONSOLE: 027170.040 NEXMON wlc_ioctl_hook: tx task started
```
Note that above shows just one config I used last, of which I know that it works for sure. I tested all other valid combinations before publishing the patch too. Make sure your receiver is capable of receiving the format of the transmitted frame (e.g. can receive the number of streams ...).

Setup `mon`:
```
$ ssh admin@<mon address>
admin@RT-AC86U:/jffs# ifconfig eth5 down
admin@RT-AC86U:/jffs# ifconfig eth6 down
admin@RT-AC86U:/jffs# rmmod dhd
admin@RT-AC86U:/jffs# find /lib -name dhd.ko -exec insmod {} \;
admin@RT-AC86U:/jffs# wl -i eth6 country US
admin@RT-AC86U:/jffs# wl -i eth6 chanspec 157/80
Chanspec set to 0xe29b
admin@RT-AC86U:/jffs# wl -i eth6 monitor 2
admin@RT-AC86U:/jffs# wl -i eth6 up
admin@RT-AC86U:/jffs# ifconfig eth6 up
admin@RT-AC86U:/jffs# ./tcpdump -i eth6 -X
tcpdump: WARNING: eth6: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth6, link-type EN10MB (Ethernet), capture size 65535 bytes
00:14:37.702238 00:c0:01:00:00:00 (oui Unknown) > 00:00:2a:00:6b:08 (oui Unknown) Null Unnumbered, ab, Flags [Command], length 56
        0x0000:  0000 abb8 fd27 0000 0000 1000 4001 9916  .....'......@...
        0x0010:  f6ad 0100 0010 1801 0200 0400 0802 2c00  ..............,.
        0x0020:  0011 2233 4455 0011 2233 4466 0011 2233  .."3DU.."3Df.."3
        0x0030:  4477 6001 dc29 69ee                      Dw`..)i.
00:14:38.200711 00:c0:01:00:00:00 (oui Unknown) > 00:00:2a:00:6b:08 (oui Unknown) Null Unnumbered, ui, Flags [Poll], length 56
        0x0000:  0000 1354 0528 0000 0000 1000 4001 9916  ...T.(......@...
        0x0010:  f6ad 0100 0010 1801 0200 0400 0802 2c00  ..............,.
        0x0020:  0011 2233 4455 0011 2233 4466 0011 2233  .."3DU.."3Df.."3
        0x0030:  4477 7001 8d3b aba4                      Dwp..;..
00:14:38.699360 00:c0:01:00:00:00 (oui Unknown) > 00:00:2a:00:6b:08 (oui Unknown) Null Unnumbered, cb, Flags [Poll], length 56
        0x0000:  0000 dbef 0c28 0000 0000 1000 4001 9916  .....(......@...
        0x0010:  f6ad 0100 0010 1801 0200 0400 0802 2c00  ..............,.
        0x0020:  0011 2233 4455 0011 2233 4466 0011 2233  .."3DU.."3Df.."3
        0x0030:  4477 8001 30da 17b0                      Dw..0...
```
In the `tcpdump` output the frames start at offset `0x1c` of the hexdump.

**Comment by Davide-Zamboni** [comment]
@jlinktu, thanks a lot! 
Now I can see all the frames coming with `./tcpdump -i eth6 -X`, anyway they seem not to be captured with the [CSI extraction tool](https://github.com/seemoo-lab/nexmon_csi).
I've tried `./makecsiparams -c 157/80 -C 4 -N 1 -b 0x08` as your suggestion but there's no packet captured using `./tcpdump -i eth6 dst port 5500 -v`

**Comment by jlinktu** [comment]
True, it seems the `nexmon_csi` patch ignores frames with a payload length of 0.
You can quickly work around this by changing the injected frame in `tx_task.sh` to something like this:
```
frame_length=28
frame_bytes='\x08\x02\x00\x00\x00\x11\x22\x33\x44\x55\x00\x11\x22\x33\x44\x66\x00\x11\x22\x33\x44\x77\x00\x00\x12\x34\x56\x78'
```

**Comment by Davide-Zamboni** [comment]
It works flawlessly, thanks a lot for the huge help!

**Comment by Qingfengxulailu** [comment]
![Uploading image.png…]()

I have tried as the up,  and at receiver:
1../makecsiparams -c 157/80 -C 0xf -N 0xf -m 00:11:22:33:44:77 -b 0x08,
2./jffs/nexutil -Ieth6 -s500 -b -l34 -vm+IB/wEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyAA==
3./usr/sbin/wl -i eth6 monitor 1\n/jffs/nexutil -Ieth6 -k\n
4./jffs/tcpdump -i eth6 -X
, no udp 10.10.10.10 -> 255.255.255.255 UDP packets 

![image](https://github.com/seemoo-lab/nexmon_tx_task/assets/34501239/f6a81865-02dc-4e3b-a155-559799d6bec9)

**Comment by Qingfengxulailu** [comment]
now at receiver, I edit './makecsiparams -c 157/80 -C 0xf -N 0xf -m 00:11:22:33:44:66 -b 0x08' it is OK. Thanks
