### ISSUE TITLE
nexutil no transmitting any packages

### ISSUE THREAD

**Issue by dhuangGH** [seemoo-lab/nexmon_tx_task#10]
I compiled a binary nexutil using the  "Build and install nexutil" section in [nexmon_tx_task](https://github.com/seemoo-lab/nexmon_tx_task) , and copy the nexutil to the router. Running nexutil with the recommended argument for 100seconds, I am expecting to transmit thousands of packages at the wireless interface, but the tx packets only show 20. 

eth7      Link encap: Ethernet  HWaddr A0:36:BC:38:7B:3C  
          inet addr:172.16.16.10  Bcast:172.16.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:6 overruns:0 frame:0
          TX packets:20 errors:0 dropped:34 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:6212 (6.0 KiB)

**One more observation,** If I run nexutil on the router without an argument via SSH, I think I should get some reminder message on expected arguments. But I get no message at all. What could go wrong? Thanks1

**Comment by jlinktu** [comment]
I recommend you to use [`tx_task.sh`](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#tx_tasksh) instead of the raw `nexutil` commands. Please read the README as a whole to understand how to use it.

**Comment by dhuangGH** [comment]
@jlinktu Thanks for your quick help! Yes, I will surely review the README closely again. 

But I just want to confirm the intended behavior of nexutil. Should it at least produce any argument reminder or help messages on router, if it is compiled properly? Thanks!

**Comment by jlinktu** [comment]
You can execute `./nexutil --help` to get a help message.

**Comment by dhuangGH** [comment]
@jlinktu  I have followed nexmon_tx_task and installed the firmwire, nexutil and tcpdump to AP and made them excitable.   "dmesg | grep NEXMON | tail -n1" seems show that the commands correctly configured.  But according to "ifconfig eth6", there is still not TX package sent out at eth6.

Here's my full pipeline:

admincp@RT-AC86U-0698:/tmp/home/root# cd /jffs
admincp@RT-AC86U-0698:/jffs# /sbin/rmmod dhd
admincp@RT-AC86U-0698:/jffs# /sbin/insmod /jffs/dhd.ko
admincp@RT-AC86U-0698:/jffs# /usr/sbin/wl -i eth6 country US
admincp@RT-AC86U-0698:/jffs# /usr/sbin/wl -i eth6 chanspec 157/80
Chanspec set to 0xe29b
admincp@RT-AC86U-0698:/jffs# /usr/sbin/wl -i eth6 up
admincp@RT-AC86U-0698:/jffs# /usr/sbin/wl -i eth6 radio on
admincp@RT-AC86U-0698:/jffs# ifconfig eth6 up
admincp@RT-AC86U-0698:/jffs# ifconfig eth6
eth6      Link encap:Ethernet  HWaddr 40:B0:76:38:06:9C  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:1 overruns:0 frame:0
          TX packets:0 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

admincp@RT-AC86U-0698:/jffs# /jffs/tx_task.sh eth6 init
done
admincp@RT-AC86U-0698:/jffs# dmesg | grep NEXMON | tail -n1
CONSOLE: 026791.576 NEXMON wlc_ioctl_hook: initialized tx task (delay 5ms, periodic 1, repetitions -1, rate 0xc2030040, frame length 28)
admincp@RT-AC86U-0698:/jffs# ifconfig eth6
eth6      Link encap:Ethernet  HWaddr 40:B0:76:38:06:9C  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:1 overruns:0 frame:0 ifconfig eth6
          TX packets:0 errors:0 dropped:12 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

admincp@RT-AC86U-0698:/jffs# /jffs/tx_task.sh eth6 start
done
admincp@RT-AC86U-0698:/jffs# dmesg | grep NEXMON | tail -n1
CONSOLE: 026891.167 NEXMON wlc_ioctl_hook: tx task started
admincp@RT-AC86U-0698:/jffs# ifconfig eth6
eth6      Link encap:Ethernet  HWaddr 40:B0:76:38:06:9C  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:1 overruns:0 frame:0
          TX packets:0 errors:0 dropped:15 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

admincp@RT-AC86U-0698:/jffs# /jffs/tx_task.sh eth6 stop
done
admincp@RT-AC86U-0698:/jffs# ifconfig eth6
eth6      Link encap:Ethernet  HWaddr 40:B0:76:38:06:9C  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:1 overruns:0 frame:0
          TX packets:0 errors:0 dropped:17 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

admincp@RT-AC86U-0698:/jffs# /jffs/tx_task.sh eth6 deinit

**Comment by jlinktu** [comment]
The frames are injected and therefore not counted.

**Comment by dhuangGH** [comment]
@jlinktu Thanks! I guess I can only verify TX by capturing at the Rx side (another RT-AC86U). Unfortunately, when I config the RX to the step of "nexutil", I got this error: " __nex_driver_io: error ret=-1 errno=95"

I am sure I have reloaded the firmwire before the RX configuration. 

I also tried the same nexutil command on the TX side, on which the tx_task.sh seem working (please see my "dmesg | grep NEXMON | tail -n1" outputs in the TX log above ). But on TX, I get the same error " __nex_driver_io: error ret=-1 errno=95" with the nexutil command.

Please see my RX pipeline below:

admincp@RT-AC86U-EFD8:/tmp/home/root# /sbin/rmmod dhd
admincp@RT-AC86U-EFD8:/tmp/home/root# /sbin/insmod /jffs/dhd.ko
admincp@RT-AC86U-EFD8:/tmp/home/root# /usr/sbin/wl -i eth6 country US
admincp@RT-AC86U-EFD8:/tmp/home/root# /usr/sbin/wl -i eth6 up
admincp@RT-AC86U-EFD8:/tmp/home/root# /usr/sbin/wl -i eth6 radio on
admincp@RT-AC86U-EFD8:/tmp/home/root# ifconfig eth6 up
admincp@RT-AC86U-EFD8:/tmp/home/root# /jffs/nexutil -Ieth6 -s500 -b -l34 -vm+IB/wEIAQBAsHY4BpwAAAAAAAAAAAAAAAAAAAAAAAAyAA==
__nex_driver_io: error ret=-1 errno=95

- The -v string above was generated by "makecsiparams -c 157/80 -C 0xf -N 0xf -m 40:B0:76:38:06:9C -b 0x08"

Do you think if there's something wrong with the firmwire or nexutil? Thanks

**Comment by jlinktu** [comment]
Have a look at https://github.com/seemoo-lab/nexmon_tx_task/issues/1

**Comment by dhuangGH** [comment]
Thanks for the link! I did learn from your routines in that post. If I understand correctly, the error may occur when the firmware is not reloaded before configuration. 

But as you may see in my logs, I did run "rmmod dhd && insmod /jffs/dhd.ko" Any other possible issues may cause the error?

Or if there's a way to confirm the status of the firmware ?

Thanks!

**Comment by dhuangGH** [comment]
@jlinktu Somehow, "rmmod dhd && insmod /jffs/dhd.ko" did not load the firmware correctly. Does this mean that there is something wrong with my "dhd.ko"? Any suggestions?

Please see below. Thanks!

admincp@RT-AC86U-EFD8:/jffs# ./nexutil -Ieth6 -V | grep -ic nexmon
0
admincp@RT-AC86U-EFD8:/jffs# /sbin/rmmod dhd
admincp@RT-AC86U-EFD8:/jffs# /sbin/insmod /jffs/dhd.ko
admincp@RT-AC86U-EFD8:/jffs# ./nexutil -Ieth6 -V | grep -ic nexmon
0
admincp@RT-AC86U-EFD8:/jffs# dmesg | grep 10.10.122.20
CONSOLE: RTE (PCIE-MSG_BUF) 10.10.122.20 (r683106) on BCM43666 r4 @ 40.0/200.0/800.0MHz
CONSOLE: 026738.760 10.10.122.20 (nexmon_tx_task: 8d55-dirty-5)
CONSOLE: RTE (PCIE-MSG_BUF) 10.10.122.20 (r683106) on BCM43664 r4 @ 40.0/200.0/800.0MHz
CONSOLE: 026738.771 10.10.122.20 (nexmon_tx_task: 8d55-dirty-5)
admincp@RT-AC86U-EFD8:/jffs# ./nexutil -Ieth6 -s500 -b -l34 -vm+ABEQAAAgCOfDYKIYywpGCXLCgAAAAAAAAAAAAAAAAAAA==
__nex_driver_io: error ret=-1 errno=95

**Comment by jlinktu** [comment]
You are trying to call an IOCTL related to CSI extractor configuration on the frame injection firmware. The patched firmwares are not interchangeable. You have to load the tx task firmware on the transmitter and CSI extractor firmware on the extractor device.

**Comment by dhuangGH** [comment]
@jlinktu  It works great now. Thank you so much!
