### ISSUE TITLE
_nex_driver_io: error ret=-1 errno=95

### ISSUE THREAD

**Issue by Qingfengxulailu** [seemoo-lab/nexmon_tx_task#2]
wiSense@RT-AC86U-9360:/jffs# ./scripts/services-start
Chanspec set to 0xe29b
__nex_driver_io: error ret=-1 errno=95
done
__nex_driver_io: error ret=-1 errno=95
done
wiSense@RT-AC86U-9360:/jffs#

**Comment by Qingfengxulailu** [comment]
is there special set at transmitter device?

**Comment by Qingfengxulailu** [comment]
the two AC86U， one router connect another？

**Comment by jlinktu** [comment]
Hi [Qingfengxulailu](https://github.com/Qingfengxulailu),
your issue description is not telling me what you are trying to do nor why you are failing to do so.
Based on the current information you provided I won't be able to help you.
Try to write a proper description of your goal, setup, and steps to recreate your problem.

**Comment by jlinktu** [comment]
You also might want to have a look at issue thread #1.

**Comment by IceNotCold** [comment]
I try to use NEXUS6P to implement injection. When I excute the "myframe.sh" file in Android terminal, I also get the error. I also don't knpw how to solve it.

**Comment by jlinktu** [comment]
This repository currently only supports the BCM4366c0 on the Asus RT-AC86U. If you want to use the same patch with a Nexus 6P you'll first have to port it to a Nexus 6P's firmware. The shell script you are referring to is also specific to the Asus router, so you would probably have to slightly modify it too to work on an Android device.

**Comment by bingwl** [comment]
Hi, I meet the same issue.
I completed the configuration of my RT-AC86U according to the guide and successfully sent the WiFi frame. Then I switch off and repower the RT-AC86U, starting with configuring the Wi-Fi interface, ie:
`ssh admin@<address of your rt-ac86u> "/usr/sbin/wl -i eth6 country US"
ssh admin@<address of your rt-ac86u> "/usr/sbin/wl -i eth6 chanspec 157/80"
ssh admin@<address of your rt-ac86u> "/usr/sbin/wl -i eth6 up"`
it succeed. But when I perform IOCTLs, i.e:
`/jffs/tx_task.sh <interface> init`
I got the same error. I had to reinstall _nexmon_tx_task_ and _nexutil_ to get back to normal. But it is frustrating to do this after every repower, is there a better solution?

**Comment by jlinktu** [comment]
Whatever you put into the `/jffs` directory should still be there after a reboot. However, when rebooting, the default kernel module gets loaded, thus, you have to perform [Install and load patched firmware](https://github.com/seemoo-lab/nexmon_tx_task#install-and-load-patched-firmware) again, or load the modified kernel module manually e.g. by running on the router: `rmmod dhd && insmod /jffs/dhd.ko`. Afterwards you can configure the interface as you did it.
Of course you can also try to automate the loading on reboot by modifying the image from Asus and replace the default dhd kernel module or modify their init scripts.

**Comment by bingwl** [comment]
Thank you very much for your reply, it solved my problem very well.
