### ISSUE TITLE
tx_router packets 0

### ISSUE THREAD

**Issue by Qingfengxulailu** [seemoo-lab/nexmon_tx_task#3]
![image](https://github.com/seemoo-lab/nexmon_tx_task/assets/34501239/e0ee2e72-bb61-4c75-9f98-83cd2962b582)

**Comment by jlinktu** [comment]
Hi [Qingfengxulailu](https://github.com/Qingfengxulailu),
your issue description is not telling me what you are trying to do nor why you are failing to do so.
Based on the current information you provided I won't be able to help you.
Try to write a proper description of your goal, setup, and steps to recreate your problem.

**Comment by Qingfengxulailu** [comment]
transmitter environment setup step:

1. install nexutil, dhd.ko, tx_task.sh to AC86U router,  
2. open permission of dhd.ko, nexutil, tx_task.sh
3.  input command as follow:
 #!/bin/sh

    /sbin/rmmod dhd
    /sbin/insmod /jffs/dhd.ko

    wl -i eth6 up
    wl -i eth6 radio on
    wl -i eth6 country US
    wl -i eth6 chanspec 157/80
    ifconfig eth6 up
    /jffs/tx_task.sh eth6 init
    /jffs/tx_task.sh eth6 start

Receiver environment:
 at another AC86U, get relatd Channel state information by tcpdump, it is null. the command as follow:
   ./makecsiparams -c 157/80 -C 0xf -N 1 -m 00:11:22:33:44:66 —b 0x08`
   ./nexutil -Ieth6 -s500 -b -l34 -v<output of makecsiparams>
   /usr/sbin/wl -i eth6 monitor 1`
   ./tcpdump -i eth6 dst port 5500 -w /tmp/mnt/<your usb name>/test.pcap`

**Comment by jlinktu** [comment]
Instead of trying to extract CSI, check first if the problem is at the transmitting or receiving side by replacing the CSI extraction with a simple monitor. [This comment](https://github.com/seemoo-lab/nexmon_tx_task/issues/1#issuecomment-1438403189) shows you the exact steps on how to configure transmitter and receiver side for this.
