### ISSUE TITLE
How to shorten the delay of repetitive transmissions to less than 1 millisecond?

### ISSUE THREAD

**Issue by IceNotCold** [seemoo-lab/nexmon_tx_task#4]
I want to use my AC86U to send NULL packets (duration less than 40 microseconds) periodically at 100 microseconds. So，I need to set the **tx_delay=0.1** in _tx_bash.sh_. However, tx_delay can only accept integers. What can I do to get the send period below 1 ms?

**Comment by jlinktu** [comment]
The way this patch works is not suited for that, as the scheduling accepts only delays in steps of 1 ms.
But you can write a nexmon patch that does not use this type of scheduling and try to get a lower period.
