### ISSUE TITLE
Does Nexmon can change the channel coding scheme of the router?

### ISSUE THREAD

**Issue by bingwl** [seemoo-lab/nexmon_tx_task#5]
I have learnt that the channel coding scheme for wifi may be BCC or LDPC codes. I would like to know if nexmon supports changing the channel coding scheme.

**Comment by jlinktu** [comment]
Following the comment on rate settings:
https://github.com/seemoo-lab/nexmon_tx_task/blob/8d550c187261c4f1a637fa2ac316dd379fb51260/utils/tx_task.sh#L78

there is a define indicating LDPC coding here:
```
#define RATES_LDPC_CODING       0x00400000
```
https://github.com/seemoo-lab/nexmon/blob/8fd5ddef14d5b0c2eb607ec25b395efa7e501a0b/patches/include/rates.h#L54

Try setting this bit to `1` in the rate argument.

**Comment by Walthard** [comment]
I would like to ask a question that may be irrelevant to this issue. Does Nexmon support turning off bit scrambling, or setting a fixed initial value for the scrambler?

**Comment by jlinktu** [comment]
Please open a dedicated issue for that.

Did you try my suggested solution for this issue?
If yes, is this solved and can be closed?

**Comment by bingwl** [comment]
Sorry for that. According to your instruction, I found the 22th bit of parameter _rt_ (in [tx_task.sh](https://github.com/seemoo-lab/nexmon_tx_task/blob/8d550c187261c4f1a637fa2ac316dd379fb51260/utils/tx_task.sh#L78)) represent the BCC or LDPC coding. So, I just manually set the 22th bit of _rt_ to 1. But the transmitted wave still BCC encoded.

**Comment by jlinktu** [comment]
To set the mentioned bit, you could replace with the following:
```
rt=$(${PRINTF} "\\\x%1x%1x\\\x00\\\x4%01x\\\xc2" ${spatial_streams} ${mcs} ${bandwidth})
```
Maybe you also have to change to a HT rate, like this:
```
rt=$(${PRINTF} "\\\x08\\\x00\\\x4%01x\\\xc1" ${bandwidth})
```
If that doesn't work one might need to activate LDPC first somehow.

**Comment by bingwl** [comment]
I replace with the  `rt=$(${PRINTF} "\\\x%1x%1x\\\x00\\\x4%01x\\\xc2" ${spatial_streams} ${mcs} ${bandwidth})` mentioned above. I use the SDR to receive the signals and recover VHT-SIG-A2 field. Unfortunately, it shows the VHT frame still uses BCC coding.

**Comment by jlinktu** [comment]
What about the second option, using HT?

**Comment by bingwl** [comment]
I tried the second option. It seems the parameters are incorrect and lead the router cannot transmit the wave (I cannot find any signals in my configured channel, though the _tx_task.sh_ can be implemented). And I also cannot receive any 802.11 packets with my WiFi dongle.

**Comment by bingwl** [comment]
After I change the last byte _c2_ to _c1_, the router can transmit the HT packets normally. But it is still BCC coding.

**Comment by jlinktu** [comment]
Right, my bad. Should have been `c1`.

There is one more simple thing that you can try. On the router run (replace `<interface>`):
```
/jffs/nexutil -I<interface> -s263 -l512 -b -v`printf "ldpc_tx\x00\x01\x00\x00\x00" | openssl enc -base64 | tr -d "\n"`
```
This calls a named IOVAR with the name `"ldpc_tx"` with the value `1 (ON)`.
It might allow transmitting with LDPC.


_To turn it `OFF (0)`:_
```
/jffs/nexutil -I<interface> -s263 -l512 -b -v`printf "ldpc_tx\x00\x00\x00\x00\x00" | openssl enc -base64 | tr -d "\n"`
```
_To set on `AUTO( -1)`:_
```
/jffs/nexutil -I<interface> -s263 -l512 -b -v`printf "ldpc_tx\x00\xff\xff\xff\xff" | openssl enc -base64 | tr -d "\n"`
```

**Comment by bingwl** [comment]
The above method works! The demodulated HT-SIG field shows packets sent are encoded by LDPC. Thank you very much for your help!
![1](https://github.com/seemoo-lab/nexmon_tx_task/assets/146060434/35694652-abcc-4348-be4e-0ce3cd8d1a7a)

**Comment by jlinktu** [comment]
Great, happy to help and thank you for reporting back.
