### ISSUE TITLE
How to Enable Single Antenna Transmission

### ISSUE THREAD

**Issue by Mojuscran** [seemoo-lab/nexmon_tx_task#6]
In my current setup, the transmitter is equipped with four antennas, but I need to limit the transmission to only one antenna. However, despite my attempts to configure the transmitter, it continues to use all four antennas simultaneously. How can the configuration be done on this project to enable transmission using only a single antenna?

**Comment by jlinktu** [comment]
Are you using [tx_task.sh ](https://github.com/seemoo-lab/nexmon_tx_task/blob/main/utils/tx_task.sh) and if yes what are your settings?
If `spatial_mode` is set to `0` and `spatial_streams` is set to `1`, the device should transmit from a single antenna.

**Comment by Mojuscran** [comment]
I did set it up this way, but when I send a packet, the receiver receives four packets simultaneously.

**Comment by jlinktu** [comment]
Four packets (frames) is different to one frame from four antennas. Please be more specific about your problem, setup, and observations.

**Comment by Mojuscran** [comment]
@jlinktu ,
Thank you for your patient guidance. Here is my transmitter configuration. Setup `tx`:
```shell
admin@RT-AC86U:/jffs# sed -n 47,58p tx_task.sh
spatial_mode=0    # 0: OFF, 1: ON, 255: AUTO, might enable STBC -> leave OFF if unwanted
periodic=0        # 0: single transmission, 1: repetitive transmissions
tx_delay=100      # delay in milliseconds between repetitive transmissions and before the first transmission
repetitions=100   # number of repetitive transmissions, -1 means infinite
bandwidth=3       # bandwidth (1, 2, 3 : 20, 40 or 80 MHz)
mcs=4             # VHT Modulation Coding Scheme
spatial_streams=1 # number of spatial streams (1 - 4)

# Data frame, To DS: 0 From DS: 1, Receiver/Destination address: 00:11:22:33:44:55, Transmitter address/BSS Id: 00:11:22:33:44:66, Source address: 00:11:22:33:44:77, 4 byte payload 0x12345678
frame_length=28
frame_bytes='\x08\x02\x00\x00\x00\x11\x22\x33\x44\x55\x00\x11\x22\x33\x44\x66\x00\x11\x22\x33\x44\x77\x00\x00\x12\x34\x56\x78'
admin@RT-AC86U:/jffs# rmmod dhd && insmod /jffs/dhd.ko
admin@RT-AC86U:/jffs# wl -i eth6 country US
admin@RT-AC86U:/jffs# wl -i eth6 chanspec 157/80
admin@RT-AC86U:/jffs# wl -i eth6 up
admin@RT-AC86U:/jffs# ifconfig eth6 up
admin@RT-AC86U:/jffs# ./tx_task.sh eth6 init
admin@RT-AC86U:/jffs# ./tx_task.sh eth6 start
```
Setup `mon`:
```shell
admin@RT-AC86U:/jffs# rmmod dhd && insmod /jffs/dhd.ko
admin@RT-AC86U:/jffs# wl -i eth6 up
admin@RT-AC86U:/jffs# wl -i eth6 radio on
admin@RT-AC86U:/jffs# ifconfig eth6 up
admin@RT-AC86U:/jffs# /jffs/nexutil -Ieth6 -s500 -b -l34 -vm+IB/wEIAQAAESIzRGYAAAAAAAAAAAAAAAAAAAAAAAAyAA==
admin@RT-AC86U:/jffs# /usr/sbin/wl -i eth6 monitor 1
admin@RT-AC86U:/jffs# /jffs/nexutil -I eth6 -s526 -i -l4 -v1
admin@RT-AC86U:/jffs# tcpdump -i eth6 -vv dst port 5500 -w /jffs/csi_data/csi.pcap
tcpdump: WARNING: eth6: no IPv4 address assigned
tcpdump: listening on eth6, link-type EN10MB (Ethernet), capture size 65535 bytes
^C16 packets captured
16 packets received by filter
0 packets dropped by kernel
```
The parameters for setting nexutil are generated by `./makecsiparams -c 157/80 -C 0xf -N 0xf -m 00:11:22:33:44:66 -b 0x08`. This is the entire process of the receiver receiving data after sending a packet. I have set the spatial stream to 1, but theoretically, the receiver should only receive 4 packets. However, it received 16 packets. What could be the reason for this?

**Comment by jlinktu** [comment]
This is not related to the transmitter side / [nexmon_tx_task](https://github.com/seemoo-lab/nexmon_tx_task). But rather a misunderstanding on your side on how to configure [nexmon_csi](https://github.com/seemoo-lab/nexmon_csi) with `makecsiparams`. As stated in its [README](https://github.com/seemoo-lab/nexmon_csi/blob/master/utils/makecsiparams/README.md):
- the argument given to `-C` is a bitmask defining for what cores (antennas) you want CSI to be extracted
- the argument given to `-N` is a bitmask defining for what spatial streams you want CSI to be extracted

As you are giving `0xf` to both of them, there will be a CSI extraction for each of the possible 4x4 antenna / spatial stream pairs resulting in 16 extractions. And therefore 16 UDPs containing them. As your transmission is a single stream, 12 of those won't contain valid data. The other 4 are valid as each antenna sees the single spatial stream you are transmitting.
If you want to extract for the single first spatial stream and a single antenna, the possible arguments are:
- `-C 0x1 -N 0x1` or
- `-C 0x2 -N 0x1` or
- `-C 0x4 -N 0x1` or
- `-C 0x8 -N 0x1`  

Or if you want to extract the first single stream for all of the four antennas you would use:
- `-C 0xf -N 0x1`

**Comment by Mojuscran** [comment]
Thank you for your careful explanation. It is now running correctly.
