### ISSUE TITLE
Does Nexmon support setting fixed initial values for the scrambler?

### ISSUE THREAD

**Issue by bingwl** [seemoo-lab/nexmon_tx_task#7]

**Comment by jlinktu** [comment]
Nexmon itself does not support this by default. But you could add an IOCTL, for example [here](https://github.com/seemoo-lab/nexmon_tx_task/blob/8d550c187261c4f1a637fa2ac316dd379fb51260/src/ioctl.c#L193), that performs the operations required to set the scrambler's init value.

The scrambler's init value might be controllable by setting parts of a PHY-register called `ScramSigCtrl` like this:
```C
/* register defines */
#define ScramSigCtrl 0x040
#define ScramSigCtrl_initStateValue_SHIFT 0
#define ScramSigCtrl_initStateValue_MASK (0x7f << ScramSigCtrl_initStateValue_SHIFT)
#define ScramSigCtrl_scramCtrlMode_SHIFT 7
#define ScramSigCtrl_scramCtrlMode_MASK (0x1 << ScramSigCtrl_scramCtrlMode_SHIFT)
#define ScramSigCtrl_scramindexctlEn_SHIFT 8
#define ScramSigCtrl_scramindexctlEn_MASK (0x1 << ScramSigCtrl_scramindexctlEn_SHIFT)
```
Set an init value and make the scrambler use it.
```C
uint init = <YOUR INIT VALUE> & 0x7f;
phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_initStateValue_MASK, init << ScramSigCtrl_initStateValue_SHIFT);
phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_scramindexctlEn_MASK, 0 << ScramSigCtrl_scramindexctlEn_SHIFT);
phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_scramCtrlMode_MASK, 1 << ScramSigCtrl_scramCtrlMode_SHIFT);
```

You can add the address of `phy_reg_mod` [here](https://github.com/seemoo-lab/nexmon/blob/29d990bdaea869cb32f5eaa2dbb7efacdcd405aa/patches/common/wrapper.c#L331) with:
```C
AT(CHIP_VER_BCM4366c0, FW_VER_ALL, 0xA17C8)
```

To reset the scrambler to default mode (free running LFSR) you would do the following:
```C
phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_scramCtrlMode_MASK, 0 << ScramSigCtrl_scramCtrlMode_SHIFT);
```
_I haven't tested if that works, please report back if it does._

**Comment by bingwl** [comment]
Thanks for your reply. But I don't know how to implement it. Here is my understanding: 
1. Copy those defined registers to a particular file. 
2. Insert 
`uint init = <YOUR INIT VALUE> & 0x7f;`
`phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_initStateValue_MASK, init << ScramSigCtrl_initStateValue_SHIFT); ` 
`phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_scramindexctlEn_MASK, 0 << ScramSigCtrl_scramindexctlEn_SHIFT);`  
`phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_scramCtrlMode_MASK, 1 << ScramSigCtrl_scramCtrlMode_SHIFT);`
after [Line 331](https://github.com/seemoo-lab/nexmon/blob/29d990bdaea869cb32f5eaa2dbb7efacdcd405aa/patches/common/wrapper.c#L331),
3. Insert 
`AT(CHIP_VER_BCM4366c0, FW_VER_ALL, 0xA17C8)`
before [Line 331](https://github.com/seemoo-lab/nexmon/blob/29d990bdaea869cb32f5eaa2dbb7efacdcd405aa/patches/common/wrapper.c#L331)
4. Re-install Nexmon to the router.
Looking forward to getting more detailed instructions.

**Comment by jlinktu** [comment]
You are mixing up a couple of things there..
Steps 1 and 2: no; define a new `case` (e.g. `433`) [here](https://github.com/seemoo-lab/nexmon_tx_task/blob/8d550c187261c4f1a637fa2ac316dd379fb51260/src/ioctl.c#L193), and put the defines and the code there.
Step 3: yes
Step 4: yes, after you made your modifications just follow [the installation process](https://github.com/seemoo-lab/nexmon_tx_task?tab=readme-ov-file#install-and-load-patched-firmware) again
Step 5: call the IOCTL you created in steps 1+2, e.g. by connecting to the router and running there `/jffs/nexutil -I<interface> -s433` (replace `<interface>`)

**Comment by bingwl** [comment]
Thanks for your help, but it seems that the parameter `pi` in 
`phy_reg_mod(pi, ScramSigCtrl, ScramSigCtrl_initStateValue_MASK, init << ScramSigCtrl_initStateValue_SHIFT);`
 is not defined. So, the installation process error. 
<img width="512" alt="屏幕截图 2023-12-25 163039" src="https://github.com/seemoo-lab/nexmon_tx_task/assets/146060434/8097b77e-acca-4144-8615-b277a4d77d65">

**Comment by jlinktu** [comment]
You can get it like this:
`wlc->hw->band->pi`

**Comment by bingwl** [comment]
Thank you very much for your help, the method is effective in controlling the initial value of the scrambler. Attention is required:
1. This IOCTL should be called only once after the device is powered up, and the scrambler will be reset to the default mode after the device is powered down.
2. There is a probability that call this IOCTL will trigger an error: 
`__nex_driver_io: error ret=-1 errno=22`
In this case, the router needs to be rebooted to recover.

**Comment by jlinktu** [comment]
Great to hear.
1. This is expected. If you want the scrambler to have a fixed init value every time the chip is power cycled you could add a hook somewhere in the start up process and set your init value there instead of using an IOCTL.
2. There might be an issue with parallel access to the PHY registers from your IOCTL and operations of the D11 core. You could suspend the D11 and tell it that you are going to access PHY registers:
Before the first `phy_reg_mod` call:
```
wlc_bmac_suspend_mac_and_wait(wlc->hw);
wlc_phyreg_enter(pi);
```
After the last `phy_reg_mod` call:
```
wlc_phyreg_exit(pi);
wlc_bmac_enable_mac(wlc->hw);
```

_The addresses for the used functions are not yet added to nexmon, at least not for the `bcm4366c0`, but I will push them in a sec. So you will need to update your local nexmon repo to make this work._

**Comment by bingwl** [comment]
> 3. Insert
>    `AT(CHIP_VER_BCM4366c0, FW_VER_ALL, 0xA17C8)`
>    before [Line 331](https://github.com/seemoo-lab/nexmon/blob/29d990bdaea869cb32f5eaa2dbb7efacdcd405aa/patches/common/wrapper.c#L331)

Do you mean I need to insert the codes like the step 3 mentioned above before these functions? For example, insert
`AT(CHIP_VER_BCM4366c0, FW_VER_ALL, 0xA17C8)`
in [here ](https://github.com/seemoo-lab/nexmon/blob/29d990bdaea869cb32f5eaa2dbb7efacdcd405aa/patches/common/wrapper.c#L691) to enable function `wlc_bmac_suspend_mac_and_wait`.

**Comment by jlinktu** [comment]
I already did that, just `git pull` your nexmon repository to add the function addresses.

The code I provided you is supposed to go right before you do the first call of `phy_reg_mod` and after the last call of `phy_reg_mod`. Something like this:
```
uint init = <YOUR INIT VALUE> & 0x7f;
wlc_bmac_suspend_mac_and_wait(wlc->hw);
wlc_phyreg_enter(wlc->hw->band->pi);
phy_reg_mod(wlc->hw->band->pi, ScramSigCtrl, ScramSigCtrl_initStateValue_MASK, init << ScramSigCtrl_initStateValue_SHIFT); 
phy_reg_mod(wlc->hw->band->pi, ScramSigCtrl, ScramSigCtrl_scramindexctlEn_MASK, 0 << ScramSigCtrl_scramindexctlEn_SHIFT);
phy_reg_mod(wlc->hw->band->pi, ScramSigCtrl, ScramSigCtrl_scramCtrlMode_MASK, 1 << ScramSigCtrl_scramCtrlMode_SHIFT);
wlc_phyreg_exit(wlc->hw->band->pi);
wlc_bmac_enable_mac(wlc->hw);
```
